version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["bin/rails", "server", "--binding", "0.0.0.0"]
  
  db:
    image: mysql:8.0
    entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: lobsters
      MYSQL_USER: lobster
      MYSQL_PASSWORD: l0bst3r
